### ISSUE TITLE
Make DB tables utf8mb4

### ISSUE THREAD

**Issue by g0morra** [Swader/nofw#12]
Hi, I was just skimming through your project and I noticed that your database tables in `nofw/data/db/cron.sql` use `DEFAULT CHARSET=utf8`.  You might want to consider using `utf8mb4` instead to avoid MySQL truncating 4 byte UTF-8 characters.

Cheers for sharing your work, it's always interesting seeing how people put things together.

**Comment by Swader** [comment]
Thanks, good point! Can you submit a PR?

**Comment by Swader** [comment]
Fixed
